Note controller feature
c1rcle/yellow-notes-backend pull request #26
Opened 2020-04-01 14:21 UTC by wkud

Fixes #24

2020-04-01 20:50 UTC, lkurzyniec requested changes

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +    public class NoteController : ControllerBase
should be plural, as route

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +                return BadRequest("Error: HttpContext.User.EmailClaim is null");
wrong response code

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +            }
all those lines should be moved to kind of authorization mechanism (`Filter`)

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +            }
DRY rule

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +                return BadRequest("Failed to create note");
wrong status code
https://www.restapitutorial.com/httpstatuscodes.html
_The request could not be understood by the server_
server understand the request, it's even valid request. should be different http code

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +            return NoContent();
after creation of a new resource, typically api returns url to that resource.
use `CreatedAtAction()`

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +    public class NoteController : ControllerBase
add `ProducesResponseType` attribute to all methods to fillup Swager docs

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Api/Controllers/NoteController.cs
> +        public async Task<IActionResult> UpdateNote([FromBody] NoteDto noteDto,
id of note should be taken from route

2020-04-01 20:50 UTC, lkurzyniec commented on YellowNotes.Core/Utility/TokenUtility.cs
> +    public static class TokenUtility
do not make class static, that is totally bad habit!
drawback of static class it that we can't unit test them

2020-04-02 09:56 UTC, lkurzyniec commented on YellowNotes.Api/Filters/ValidateHttpContextClaimsFilter.cs
> +            context.Result = new BadRequestObjectResult(
It can't be BadRequest. when claims don't have email it means that user is not authenticated.

2020-04-02 09:58 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +                options.Filters.Add(typeof(ValidateHttpContextClaimsFilter));
I think we can merge those two files, those two code snippets.

2020-04-02 09:59 UTC, lkurzyniec commented on YellowNotes.Api/Filters/ValidateTokenFilter.cs
> +            var controller = context.Controller as ControllerBase;
I'm not sure right now, I'm giving 80% that `context` has `Request.Headers`, we don't need `ControllerBase` here

2020-04-02 10:00 UTC, lkurzyniec requested changes

2020-04-02 10:00 UTC, lkurzyniec commented on YellowNotes.Core/Utility/TokenUtility.cs
> +                return null;
missing curly brackets.

2020-04-02 16:01 UTC, filip-wan submitted a review, later dismissed

2020-04-02 17:11 UTC, filip-wan approved these changes

2020-04-02 17:15 UTC, merged