Email service feature
c1rcle/yellow-notes-backend pull request #6
Opened 2020-03-19 19:44 UTC by jaqb8

Fixes #4

2020-03-20 07:58 UTC, lkurzyniec commented
This PR contains only package changes, where is the logic? 🤔

2020-03-21 13:51 UTC, c1rcle requested changes

2020-03-21 13:51 UTC, c1rcle commented on YellowNotes.Api/Startup.cs
> +            services.AddTransient<YellowNotes.Core.Services.IEmailService, YellowNotes.Core.Services.EmailService>();
Tutaj daj `using YellowNotes.Core.Services;`, to nie trzeba będzie pisać tych długich namespace'ów.

2020-03-21 13:51 UTC, c1rcle commented on YellowNotes.Core/Services/EmailService.cs
> +        public async Task SendEmail(string fromEmailAddress, string toEmailAddress, string subject, string message)
Wydaje mi się że zdecydowanie bardziej sensowne będzie wydzielenie tego do osobnego obiektu. Na przykład `EmailMessage`.

2020-03-21 13:51 UTC, c1rcle commented on YellowNotes.Core/Services/IEmailService.cs
> +            );
Wtedy będziemy mogli to normalnie zrobić w jednej linijce.

2020-03-21 13:51 UTC, c1rcle commented on YellowNotes.Core/Services/EmailService.cs
> +                await client.DisconnectAsync(true).ConfigureAwait(false);
Fajnie by było gdyby to nie było zhardkodowane. Można zrobić singleton konfiguracyjny, to w sumie miałem na myśli. [Tutaj przykład](https://dotnetcoretutorials.com/2017/11/02/using-mailkit-send-receive-email-asp-net-core/).

2020-03-21 20:05 UTC, lkurzyniec requested changes

2020-03-21 20:05 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +                await client.ConnectAsync("smpt.host", 000, false).ConfigureAwait(false);
in .net core we don't need `ConfigureAwait()`, there is no problem with synchronization context.

when you are creating a package, that would be consumed by other people, then you don't know who will be the consumer, it could be either .net core or full framework. .net core doesn't have a problem with synchronization context, but full framework have. in such case you have to add `ConfigureAwait()`.

In your case, you are the only one consumer, so adding `ConfigureAwait()` is redundant.

2020-03-21 20:05 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +                await client.ConnectAsync("smpt.host", 000, false).ConfigureAwait(false);
All variables such as smtp address, port, login, pass should goes to `appsettings.json` file.

2020-03-21 20:05 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +        public async Task SendEmail(string fromEmailAddress, string toEmailAddress, string subject, string message)
It's better to create `model` rather than multiple parameters. In case of model, when we need to add one more parameter, then we just add it to model and then adjust the method. In case of multiple parameters, we need to modify much more places, ie interface

2020-03-21 20:05 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +        public async Task SendEmail(string fromEmailAddress, string toEmailAddress, string subject, string message)
Add also `CancellationToken` as a parameter and then consume it in all `Async` methods.

2020-03-21 20:05 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +            services.AddTransient<YellowNotes.Core.Services.IEmailService, YellowNotes.Core.Services.EmailService>();
namespaces should goes to usings.

2020-03-22 00:17 UTC, lkurzyniec commented on YellowNotes.Core/Email/EmailConfiguration.cs
> +    public class EmailConfiguration : IEmailConfiguration
There is no need to create interface for dto, models, configurations etc, because there is no business logic.

2020-03-22 00:18 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +            services.AddSingleton<IEmailConfiguration>(Configuration.GetSection("EmailConfiguration").Get<EmailConfiguration>());
Typically we configure in such way configurations: `services.Configure<SomeConfiguration>(_configuration.GetSection("SomeSection"));`

2020-03-22 00:21 UTC, lkurzyniec submitted a review, later dismissed

2020-03-22 17:58 UTC, lkurzyniec requested changes

2020-03-22 17:58 UTC, lkurzyniec commented on YellowNotes.Core/Email/EmailMessage.cs
> +        public string content { get; set; }
It's C# - all CamelCase for properties

2020-03-22 17:58 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +		        await client.SendAsync(email, cancellationToken);
Incorrect indentation.

2020-03-22 17:58 UTC, lkurzyniec commented on YellowNotes.Core/Services/EmailService.cs
> +        public EmailService(EmailConfiguration emailConfiguration)
Does the injection of `EmailConfiguration` works? I'm not sure, please check it!

2020-03-22 17:58 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +            services.AddTransient<IEmailService, EmailService>();
This can be registered as a singleton. Now the question is why. Can you figure out? ;)

2020-03-22 18:08 UTC, c1rcle commented on YellowNotes.Core/Services/EmailService.cs
> +        private readonly EmailConfiguration _emailConfiguration;
Let's stick to a consistent naming convention that is already present in this repository. I don't like this one for various reasons, many of which are described [here](https://stackoverflow.com/a/17937309).

2020-03-22 20:18 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +            services.AddTransient<IEmailService, EmailService>();
It doesn't persist any state (don't have any fields). Registering it as a singleton is a way for better performance.

2020-03-22 20:19 UTC, lkurzyniec commented on YellowNotes.Api/Startup.cs
> +            services.AddTransient<IEmailService, EmailService>();
❗️

2020-03-22 20:55 UTC, lkurzyniec approved these changes

2020-03-22 20:57 UTC, c1rcle approved these changes

2020-03-22 20:58 UTC, merged